//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5DemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class programme
    {
        public programme()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ProgrammeId { get; set; }
        public string ProgrammeName { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
